// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ContractsDbContext))]
    [Migration("20210323115322_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Domain.BillObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("ContractId")
                        .HasColumnType("integer");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RfSubjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.HasIndex("RfSubjectId");

                    b.ToTable("BillObjects");
                });

            modelBuilder.Entity("Domain.BillObjectToEnergyLinkObject", b =>
                {
                    b.Property<int>("BillObjectId")
                        .HasColumnType("integer");

                    b.Property<int>("EnergyLinkObjectId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SDate")
                        .HasColumnType("Date");

                    b.Property<DateTime?>("EDate")
                        .HasColumnType("Date");

                    b.HasKey("BillObjectId", "EnergyLinkObjectId", "SDate");

                    b.HasIndex("EnergyLinkObjectId");

                    b.ToTable("BillObjectToEnergyLinkObjects");
                });

            modelBuilder.Entity("Domain.BillParam", b =>
                {
                    b.Property<int>("EnergyLinkObjectToBillPointId")
                        .HasColumnType("integer");

                    b.Property<int>("BillParamType")
                        .HasColumnType("integer");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("EnergyLinkObjectToBillPointId", "BillParamType");

                    b.ToTable("BillParams");
                });

            modelBuilder.Entity("Domain.BillPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.ToTable("BillPoints");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Guid = new Guid("b8d40d2b-b9f2-463f-a3e8-467dcfbb48ea"),
                            Name = "bp1"
                        },
                        new
                        {
                            Id = 2,
                            Guid = new Guid("2ee047a6-d87c-44b7-9e0e-f89bd526b1c3"),
                            Name = "bp2"
                        },
                        new
                        {
                            Id = 3,
                            Guid = new Guid("235f7a97-ac8d-47c9-bead-528ff21a005f"),
                            Name = "bp3"
                        });
                });

            modelBuilder.Entity("Domain.ContractParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("ContractId")
                        .HasColumnType("integer");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<int>("ParticipantType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("ContractParticipants");
                });

            modelBuilder.Entity("Domain.EnergyLinkObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EnergyLinkObjects");
                });

            modelBuilder.Entity("Domain.EnergyLinkObjectToBillPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("BillPointId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EDate")
                        .HasColumnType("Date");

                    b.Property<int>("EnergyLinkObjectId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SDate")
                        .HasColumnType("Date");

                    b.HasKey("Id");

                    b.HasIndex("BillPointId");

                    b.HasIndex("EnergyLinkObjectId");

                    b.ToTable("EnergyLinkObjectToBillPoint");
                });

            modelBuilder.Entity("Domain.Entities.BillPointRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("ContractKind")
                        .HasColumnType("integer");

                    b.Property<int>("ContractType")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EntrySign")
                        .HasColumnType("integer");

                    b.Property<int>("OrganizationTypeSide1")
                        .HasColumnType("integer");

                    b.Property<int>("OrganizationTypeSide2")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("BillPointRules");
                });

            modelBuilder.Entity("Domain.Entities.BillSideToBillPoint", b =>
                {
                    b.Property<int>("EnergyLinkObjectId")
                        .HasColumnType("integer");

                    b.Property<int>("BillPointId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SDate")
                        .HasColumnType("Date");

                    b.Property<DateTime?>("EDate")
                        .HasColumnType("Date");

                    b.Property<int>("TypeSide")
                        .HasColumnType("integer");

                    b.HasKey("EnergyLinkObjectId", "BillPointId", "SDate");

                    b.HasIndex("BillPointId");

                    b.ToTable("BillSideToBillPoints");
                });

            modelBuilder.Entity("Domain.Entities.ContractDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DocumentType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EActionDate")
                        .HasColumnType("Date");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SActionDate")
                        .HasColumnType("Date");

                    b.Property<DateTime>("SignDate")
                        .HasColumnType("Date");

                    b.HasKey("Id");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.ToTable("ContractDocument");

                    b.HasDiscriminator<int>("DocumentType");
                });

            modelBuilder.Entity("Domain.Entities.RfSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CodeAts")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.ToTable("RfSubjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "30",
                            CodeAts = "12",
                            Guid = new Guid("d8162092-2702-4ae3-a4f3-fbd1a85b6069"),
                            Name = "Астраханская область"
                        },
                        new
                        {
                            Id = 2,
                            Code = "26",
                            CodeAts = "07",
                            Guid = new Guid("99b12c1a-5df8-4f13-96b9-1a46f74ac7bc"),
                            Name = "Ставропольский край"
                        },
                        new
                        {
                            Id = 3,
                            Code = "23",
                            CodeAts = "03",
                            Guid = new Guid("8164c992-8c0b-42cb-bbb7-3b46461146cc"),
                            Name = "Краснодарский край"
                        });
                });

            modelBuilder.Entity("Domain.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int?>("AcsId")
                        .HasColumnType("integer");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<string>("LongName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("OrganizationType")
                        .HasColumnType("integer");

                    b.Property<int?>("ParentOrganizationId")
                        .HasColumnType("integer");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.HasIndex("ParentOrganizationId");

                    b.ToTable("Organizations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Guid = new Guid("1b55b6f5-0e97-4764-8b33-65b80860b63f"),
                            LongName = "ТНЭ",
                            OrganizationType = 1,
                            ShortName = "ТНЭ"
                        },
                        new
                        {
                            Id = 2,
                            Guid = new Guid("f891250d-0d9f-43cf-b5fd-47e8c027eeee"),
                            LongName = "КТК",
                            OrganizationType = 4,
                            ShortName = "КТК"
                        },
                        new
                        {
                            Id = 3,
                            Guid = new Guid("85f9fbb7-e680-46b6-8c91-ce2c35dd4193"),
                            LongName = "Дружба",
                            OrganizationType = 4,
                            ShortName = "Дружба"
                        },
                        new
                        {
                            Id = 4,
                            Guid = new Guid("043210b2-d3a0-4fc2-b505-735558c48a07"),
                            LongName = "Рога и копыта",
                            OrganizationType = 0,
                            ShortName = "Рога и копыта"
                        },
                        new
                        {
                            Id = 5,
                            Guid = new Guid("f97736b3-fc4d-466c-8c93-22c4c020a5fc"),
                            LongName = "Башкирэнерго",
                            OrganizationType = 3,
                            ShortName = "Башкирэнерго"
                        });
                });

            modelBuilder.Entity("Domain.Contract", b =>
                {
                    b.HasBaseType("Domain.Entities.ContractDocument");

                    b.Property<int>("ContractKind")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Domain.Entities.SubContract", b =>
                {
                    b.HasBaseType("Domain.Entities.ContractDocument");

                    b.Property<int>("ContractDocumentId")
                        .HasColumnType("integer");

                    b.HasIndex("ContractDocumentId");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Domain.BillObject", b =>
                {
                    b.HasOne("Domain.Contract", null)
                        .WithMany("BillObjects")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.RfSubject", "RfSubject")
                        .WithMany()
                        .HasForeignKey("RfSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RfSubject");
                });

            modelBuilder.Entity("Domain.BillObjectToEnergyLinkObject", b =>
                {
                    b.HasOne("Domain.BillObject", "BillObject")
                        .WithMany("BillObjectsToEnergyLinkObjects")
                        .HasForeignKey("BillObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.EnergyLinkObject", "EnergyLinkObject")
                        .WithMany("BillObjectsToEnergyLinkObjects")
                        .HasForeignKey("EnergyLinkObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BillObject");

                    b.Navigation("EnergyLinkObject");
                });

            modelBuilder.Entity("Domain.BillParam", b =>
                {
                    b.HasOne("Domain.EnergyLinkObjectToBillPoint", "EnergyLinkObjectToBillPoint")
                        .WithMany("BillParams")
                        .HasForeignKey("EnergyLinkObjectToBillPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnergyLinkObjectToBillPoint");
                });

            modelBuilder.Entity("Domain.ContractParticipant", b =>
                {
                    b.HasOne("Domain.Contract", null)
                        .WithMany("ContractParticipants")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Domain.EnergyLinkObjectToBillPoint", b =>
                {
                    b.HasOne("Domain.BillPoint", "BillPoint")
                        .WithMany("EnergyLinkObjectsToBillPoints")
                        .HasForeignKey("BillPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.EnergyLinkObject", "EnergyLinkObject")
                        .WithMany("EnergyLinkObjectsToBillPoints")
                        .HasForeignKey("EnergyLinkObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BillPoint");

                    b.Navigation("EnergyLinkObject");
                });

            modelBuilder.Entity("Domain.Entities.BillSideToBillPoint", b =>
                {
                    b.HasOne("Domain.BillPoint", "BillPoint")
                        .WithMany("BillSideToBillPoints")
                        .HasForeignKey("BillPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.EnergyLinkObject", "EnergyLinkObject")
                        .WithMany("BillSideToBillPoints")
                        .HasForeignKey("EnergyLinkObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BillPoint");

                    b.Navigation("EnergyLinkObject");
                });

            modelBuilder.Entity("Domain.Organization", b =>
                {
                    b.HasOne("Domain.Organization", "ParentOrganization")
                        .WithMany("ChildOrganizations")
                        .HasForeignKey("ParentOrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentOrganization");
                });

            modelBuilder.Entity("Domain.Entities.SubContract", b =>
                {
                    b.HasOne("Domain.Contract", "Contract")
                        .WithMany("SubContracts")
                        .HasForeignKey("ContractDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("Domain.BillObject", b =>
                {
                    b.Navigation("BillObjectsToEnergyLinkObjects");
                });

            modelBuilder.Entity("Domain.BillPoint", b =>
                {
                    b.Navigation("BillSideToBillPoints");

                    b.Navigation("EnergyLinkObjectsToBillPoints");
                });

            modelBuilder.Entity("Domain.EnergyLinkObject", b =>
                {
                    b.Navigation("BillObjectsToEnergyLinkObjects");

                    b.Navigation("BillSideToBillPoints");

                    b.Navigation("EnergyLinkObjectsToBillPoints");
                });

            modelBuilder.Entity("Domain.EnergyLinkObjectToBillPoint", b =>
                {
                    b.Navigation("BillParams");
                });

            modelBuilder.Entity("Domain.Organization", b =>
                {
                    b.Navigation("ChildOrganizations");
                });

            modelBuilder.Entity("Domain.Contract", b =>
                {
                    b.Navigation("BillObjects");

                    b.Navigation("ContractParticipants");

                    b.Navigation("SubContracts");
                });
#pragma warning restore 612, 618
        }
    }
}
