Build started...
Build succeeded.
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "BillPoints" (
    "Id" integer NOT NULL,
    "Name" text NULL,
    "TnePointId" integer NOT NULL,
    CONSTRAINT "PK_BillPoints" PRIMARY KEY ("Id")
);

CREATE TABLE "ContractDocument" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "CreatedAt" timestamp without time zone NOT NULL,
    "CreatedBy" text NULL,
    "DocumentNumber" text NOT NULL,
    "SignDate" timestamp without time zone NOT NULL,
    "SActionDate" timestamp without time zone NOT NULL,
    "EActionDate" timestamp without time zone NULL,
    "ContractType" integer NOT NULL,
    "ContractKind" integer NULL,
    "ContractDocumentId" integer NULL,
    CONSTRAINT "PK_ContractDocument" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ContractDocument_ContractDocument_ContractDocumentId" FOREIGN KEY ("ContractDocumentId") REFERENCES "ContractDocument" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "EnergyLinkObjects" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    CONSTRAINT "PK_EnergyLinkObjects" PRIMARY KEY ("Id")
);

CREATE TABLE "Organizations" (
    "Id" integer NOT NULL,
    "Name" text NULL,
    "OrganizationType" integer NOT NULL,
    CONSTRAINT "PK_Organizations" PRIMARY KEY ("Id")
);

CREATE TABLE "RfSubjects" (
    "Id" integer NOT NULL,
    "Name" character varying(255) NULL,
    "Code" character varying(50) NULL,
    "CodeAts" text NULL,
    CONSTRAINT "PK_RfSubjects" PRIMARY KEY ("Id")
);

CREATE TABLE "BillSideToBillPoints" (
    "EnergyLinkObjectId" integer NOT NULL,
    "BillPointId" integer NOT NULL,
    "SDate" timestamp without time zone NOT NULL,
    "EDate" timestamp without time zone NULL,
    "TypeSide" integer NOT NULL,
    CONSTRAINT "PK_BillSideToBillPoints" PRIMARY KEY ("EnergyLinkObjectId", "BillPointId", "SDate"),
    CONSTRAINT "FK_BillSideToBillPoints_BillPoints_BillPointId" FOREIGN KEY ("BillPointId") REFERENCES "BillPoints" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_BillSideToBillPoints_EnergyLinkObjects_EnergyLinkObjectId" FOREIGN KEY ("EnergyLinkObjectId") REFERENCES "EnergyLinkObjects" ("Id") ON DELETE CASCADE
);

CREATE TABLE "EnergyLinkObjectToBillPoint" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "EnergyLinkObjectId" integer NOT NULL,
    "BillPointId" integer NOT NULL,
    "SDate" timestamp without time zone NOT NULL,
    "EDate" timestamp without time zone NULL,
    CONSTRAINT "PK_EnergyLinkObjectToBillPoint" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EnergyLinkObjectToBillPoint_BillPoints_BillPointId" FOREIGN KEY ("BillPointId") REFERENCES "BillPoints" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_EnergyLinkObjectToBillPoint_EnergyLinkObjects_EnergyLinkObj~" FOREIGN KEY ("EnergyLinkObjectId") REFERENCES "EnergyLinkObjects" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ContractParticipants" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "ParticipantType" integer NOT NULL,
    "OrganizationId" integer NULL,
    "ContractId" integer NOT NULL,
    CONSTRAINT "PK_ContractParticipants" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ContractParticipants_ContractDocument_ContractId" FOREIGN KEY ("ContractId") REFERENCES "ContractDocument" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ContractParticipants_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "BillObjects" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    "ContractId" integer NOT NULL,
    "RfSubjectId" integer NOT NULL,
    CONSTRAINT "PK_BillObjects" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_BillObjects_ContractDocument_ContractId" FOREIGN KEY ("ContractId") REFERENCES "ContractDocument" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_BillObjects_RfSubjects_RfSubjectId" FOREIGN KEY ("RfSubjectId") REFERENCES "RfSubjects" ("Id") ON DELETE CASCADE
);

CREATE TABLE "BillParams" (
    "EnergyLinkObjectToBillPointId" integer NOT NULL,
    "BillParamType" integer NOT NULL,
    "Value" integer NOT NULL,
    CONSTRAINT "PK_BillParams" PRIMARY KEY ("EnergyLinkObjectToBillPointId", "BillParamType"),
    CONSTRAINT "FK_BillParams_EnergyLinkObjectToBillPoint_EnergyLinkObjectToBi~" FOREIGN KEY ("EnergyLinkObjectToBillPointId") REFERENCES "EnergyLinkObjectToBillPoint" ("Id") ON DELETE CASCADE
);

CREATE TABLE "BillObjectToEnergyLinkObjects" (
    "EnergyLinkObjectId" integer NOT NULL,
    "BillObjectId" integer NOT NULL,
    "SDate" timestamp without time zone NOT NULL,
    "EDate" timestamp without time zone NULL,
    CONSTRAINT "PK_BillObjectToEnergyLinkObjects" PRIMARY KEY ("BillObjectId", "EnergyLinkObjectId", "SDate"),
    CONSTRAINT "FK_BillObjectToEnergyLinkObjects_BillObjects_BillObjectId" FOREIGN KEY ("BillObjectId") REFERENCES "BillObjects" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_BillObjectToEnergyLinkObjects_EnergyLinkObjects_EnergyLinkO~" FOREIGN KEY ("EnergyLinkObjectId") REFERENCES "EnergyLinkObjects" ("Id") ON DELETE CASCADE
);

INSERT INTO "BillPoints" ("Id", "Name", "TnePointId")
VALUES (1, 'bp1', 1);
INSERT INTO "BillPoints" ("Id", "Name", "TnePointId")
VALUES (2, 'bp1', 2);
INSERT INTO "BillPoints" ("Id", "Name", "TnePointId")
VALUES (3, 'bp1', 3);

INSERT INTO "Organizations" ("Id", "Name", "OrganizationType")
VALUES (1, 'ТНЭ', 1);
INSERT INTO "Organizations" ("Id", "Name", "OrganizationType")
VALUES (2, 'КТК', 4);
INSERT INTO "Organizations" ("Id", "Name", "OrganizationType")
VALUES (3, 'Дружба', 4);
INSERT INTO "Organizations" ("Id", "Name", "OrganizationType")
VALUES (4, 'Рога и копыта', 0);
INSERT INTO "Organizations" ("Id", "Name", "OrganizationType")
VALUES (5, 'Башкирэнерго', 3);

INSERT INTO "RfSubjects" ("Id", "Code", "CodeAts", "Name")
VALUES (1, '30', '12', 'Астраханская область');
INSERT INTO "RfSubjects" ("Id", "Code", "CodeAts", "Name")
VALUES (2, '26', '07', 'Ставропольский край');
INSERT INTO "RfSubjects" ("Id", "Code", "CodeAts", "Name")
VALUES (3, '23', '03', 'Краснодарский край');

CREATE INDEX "IX_BillObjects_ContractId" ON "BillObjects" ("ContractId");

CREATE INDEX "IX_BillObjects_RfSubjectId" ON "BillObjects" ("RfSubjectId");

CREATE INDEX "IX_BillObjectToEnergyLinkObjects_EnergyLinkObjectId" ON "BillObjectToEnergyLinkObjects" ("EnergyLinkObjectId");

CREATE INDEX "IX_BillSideToBillPoints_BillPointId" ON "BillSideToBillPoints" ("BillPointId");

CREATE INDEX "IX_ContractDocument_ContractDocumentId" ON "ContractDocument" ("ContractDocumentId");

CREATE INDEX "IX_ContractParticipants_ContractId" ON "ContractParticipants" ("ContractId");

CREATE INDEX "IX_ContractParticipants_OrganizationId" ON "ContractParticipants" ("OrganizationId");

CREATE INDEX "IX_EnergyLinkObjectToBillPoint_BillPointId" ON "EnergyLinkObjectToBillPoint" ("BillPointId");

CREATE INDEX "IX_EnergyLinkObjectToBillPoint_EnergyLinkObjectId" ON "EnergyLinkObjectToBillPoint" ("EnergyLinkObjectId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210319085334_init', '5.0.2');

COMMIT;


