Build started...
Build succeeded.
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "BillPointRules" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Description" text NOT NULL,
    "ContractType" integer NOT NULL,
    "ContractKind" integer NOT NULL,
    "OrganizationTypeSide1" integer NOT NULL,
    "OrganizationTypeSide2" integer NOT NULL,
    "EntrySign" integer NOT NULL,
    CONSTRAINT "PK_BillPointRules" PRIMARY KEY ("Id")
);

CREATE TABLE "BillPoints" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(255) NULL,
    "Guid" uuid NOT NULL,
    CONSTRAINT "PK_BillPoints" PRIMARY KEY ("Id")
);

CREATE TABLE "ContractDocument" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Guid" uuid NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "CreatedBy" text NULL,
    "DocumentNumber" text NOT NULL,
    "SignDate" Date NOT NULL,
    "SActionDate" Date NOT NULL,
    "EActionDate" Date NULL,
    "DocumentType" integer NOT NULL,
    "ContractKind" integer NULL,
    "ContractDocumentId" integer NULL,
    CONSTRAINT "PK_ContractDocument" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ContractDocument_ContractDocument_ContractDocumentId" FOREIGN KEY ("ContractDocumentId") REFERENCES "ContractDocument" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "EnergyLinkObjects" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    CONSTRAINT "PK_EnergyLinkObjects" PRIMARY KEY ("Id")
);

CREATE TABLE "Organizations" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "ShortName" character varying(255) NOT NULL,
    "LongName" character varying(1024) NOT NULL,
    "AcsId" integer NULL,
    "OrganizationType" integer NOT NULL,
    "ParentOrganizationId" integer NULL,
    "Guid" uuid NOT NULL,
    CONSTRAINT "PK_Organizations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Organizations_Organizations_ParentOrganizationId" FOREIGN KEY ("ParentOrganizationId") REFERENCES "Organizations" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "RfSubjects" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(255) NOT NULL,
    "Code" character varying(50) NOT NULL,
    "CodeAts" text NOT NULL,
    "Guid" uuid NOT NULL,
    CONSTRAINT "PK_RfSubjects" PRIMARY KEY ("Id")
);

CREATE TABLE "BillSideToBillPoints" (
    "EnergyLinkObjectId" integer NOT NULL,
    "BillPointId" integer NOT NULL,
    "SDate" Date NOT NULL,
    "EDate" Date NULL,
    "TypeSide" integer NOT NULL,
    CONSTRAINT "PK_BillSideToBillPoints" PRIMARY KEY ("EnergyLinkObjectId", "BillPointId", "SDate"),
    CONSTRAINT "FK_BillSideToBillPoints_BillPoints_BillPointId" FOREIGN KEY ("BillPointId") REFERENCES "BillPoints" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_BillSideToBillPoints_EnergyLinkObjects_EnergyLinkObjectId" FOREIGN KEY ("EnergyLinkObjectId") REFERENCES "EnergyLinkObjects" ("Id") ON DELETE CASCADE
);

CREATE TABLE "EnergyLinkObjectToBillPoint" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "EnergyLinkObjectId" integer NOT NULL,
    "BillPointId" integer NOT NULL,
    "SDate" Date NOT NULL,
    "EDate" Date NULL,
    CONSTRAINT "PK_EnergyLinkObjectToBillPoint" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EnergyLinkObjectToBillPoint_BillPoints_BillPointId" FOREIGN KEY ("BillPointId") REFERENCES "BillPoints" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_EnergyLinkObjectToBillPoint_EnergyLinkObjects_EnergyLinkObj~" FOREIGN KEY ("EnergyLinkObjectId") REFERENCES "EnergyLinkObjects" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ContractParticipants" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "ParticipantType" integer NOT NULL,
    "OrganizationId" integer NULL,
    "ContractId" integer NOT NULL,
    CONSTRAINT "PK_ContractParticipants" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ContractParticipants_ContractDocument_ContractId" FOREIGN KEY ("ContractId") REFERENCES "ContractDocument" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ContractParticipants_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "BillObjects" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "ContractId" integer NOT NULL,
    "RfSubjectId" integer NOT NULL,
    "Guid" uuid NOT NULL,
    CONSTRAINT "PK_BillObjects" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_BillObjects_ContractDocument_ContractId" FOREIGN KEY ("ContractId") REFERENCES "ContractDocument" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_BillObjects_RfSubjects_RfSubjectId" FOREIGN KEY ("RfSubjectId") REFERENCES "RfSubjects" ("Id") ON DELETE CASCADE
);

CREATE TABLE "BillParams" (
    "EnergyLinkObjectToBillPointId" integer NOT NULL,
    "BillParamType" integer NOT NULL,
    "Value" integer NOT NULL,
    CONSTRAINT "PK_BillParams" PRIMARY KEY ("EnergyLinkObjectToBillPointId", "BillParamType"),
    CONSTRAINT "FK_BillParams_EnergyLinkObjectToBillPoint_EnergyLinkObjectToBi~" FOREIGN KEY ("EnergyLinkObjectToBillPointId") REFERENCES "EnergyLinkObjectToBillPoint" ("Id") ON DELETE CASCADE
);

CREATE TABLE "BillObjectToEnergyLinkObjects" (
    "EnergyLinkObjectId" integer NOT NULL,
    "BillObjectId" integer NOT NULL,
    "SDate" Date NOT NULL,
    "EDate" Date NULL,
    CONSTRAINT "PK_BillObjectToEnergyLinkObjects" PRIMARY KEY ("BillObjectId", "EnergyLinkObjectId", "SDate"),
    CONSTRAINT "FK_BillObjectToEnergyLinkObjects_BillObjects_BillObjectId" FOREIGN KEY ("BillObjectId") REFERENCES "BillObjects" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_BillObjectToEnergyLinkObjects_EnergyLinkObjects_EnergyLinkO~" FOREIGN KEY ("EnergyLinkObjectId") REFERENCES "EnergyLinkObjects" ("Id") ON DELETE CASCADE
);

INSERT INTO "BillPoints" ("Id", "Guid", "Name")
VALUES (1, 'b8d40d2b-b9f2-463f-a3e8-467dcfbb48ea', 'bp1');
INSERT INTO "BillPoints" ("Id", "Guid", "Name")
VALUES (2, '2ee047a6-d87c-44b7-9e0e-f89bd526b1c3', 'bp2');
INSERT INTO "BillPoints" ("Id", "Guid", "Name")
VALUES (3, '235f7a97-ac8d-47c9-bead-528ff21a005f', 'bp3');

INSERT INTO "Organizations" ("Id", "AcsId", "Guid", "LongName", "OrganizationType", "ParentOrganizationId", "ShortName")
VALUES (1, NULL, '1b55b6f5-0e97-4764-8b33-65b80860b63f', 'ТНЭ', 1, NULL, 'ТНЭ');
INSERT INTO "Organizations" ("Id", "AcsId", "Guid", "LongName", "OrganizationType", "ParentOrganizationId", "ShortName")
VALUES (2, NULL, 'f891250d-0d9f-43cf-b5fd-47e8c027eeee', 'КТК', 4, NULL, 'КТК');
INSERT INTO "Organizations" ("Id", "AcsId", "Guid", "LongName", "OrganizationType", "ParentOrganizationId", "ShortName")
VALUES (3, NULL, '85f9fbb7-e680-46b6-8c91-ce2c35dd4193', 'Дружба', 4, NULL, 'Дружба');
INSERT INTO "Organizations" ("Id", "AcsId", "Guid", "LongName", "OrganizationType", "ParentOrganizationId", "ShortName")
VALUES (4, NULL, '043210b2-d3a0-4fc2-b505-735558c48a07', 'Рога и копыта', 0, NULL, 'Рога и копыта');
INSERT INTO "Organizations" ("Id", "AcsId", "Guid", "LongName", "OrganizationType", "ParentOrganizationId", "ShortName")
VALUES (5, NULL, 'f97736b3-fc4d-466c-8c93-22c4c020a5fc', 'Башкирэнерго', 3, NULL, 'Башкирэнерго');

INSERT INTO "RfSubjects" ("Id", "Code", "CodeAts", "Guid", "Name")
VALUES (1, '30', '12', 'd8162092-2702-4ae3-a4f3-fbd1a85b6069', 'Астраханская область');
INSERT INTO "RfSubjects" ("Id", "Code", "CodeAts", "Guid", "Name")
VALUES (2, '26', '07', '99b12c1a-5df8-4f13-96b9-1a46f74ac7bc', 'Ставропольский край');
INSERT INTO "RfSubjects" ("Id", "Code", "CodeAts", "Guid", "Name")
VALUES (3, '23', '03', '8164c992-8c0b-42cb-bbb7-3b46461146cc', 'Краснодарский край');

CREATE INDEX "IX_BillObjects_ContractId" ON "BillObjects" ("ContractId");

CREATE UNIQUE INDEX "IX_BillObjects_Guid" ON "BillObjects" ("Guid");

CREATE INDEX "IX_BillObjects_RfSubjectId" ON "BillObjects" ("RfSubjectId");

CREATE INDEX "IX_BillObjectToEnergyLinkObjects_EnergyLinkObjectId" ON "BillObjectToEnergyLinkObjects" ("EnergyLinkObjectId");

CREATE UNIQUE INDEX "IX_BillPoints_Guid" ON "BillPoints" ("Guid");

CREATE INDEX "IX_BillSideToBillPoints_BillPointId" ON "BillSideToBillPoints" ("BillPointId");

CREATE INDEX "IX_ContractDocument_ContractDocumentId" ON "ContractDocument" ("ContractDocumentId");

CREATE UNIQUE INDEX "IX_ContractDocument_Guid" ON "ContractDocument" ("Guid");

CREATE INDEX "IX_ContractParticipants_ContractId" ON "ContractParticipants" ("ContractId");

CREATE INDEX "IX_ContractParticipants_OrganizationId" ON "ContractParticipants" ("OrganizationId");

CREATE INDEX "IX_EnergyLinkObjectToBillPoint_BillPointId" ON "EnergyLinkObjectToBillPoint" ("BillPointId");

CREATE INDEX "IX_EnergyLinkObjectToBillPoint_EnergyLinkObjectId" ON "EnergyLinkObjectToBillPoint" ("EnergyLinkObjectId");

CREATE UNIQUE INDEX "IX_Organizations_Guid" ON "Organizations" ("Guid");

CREATE INDEX "IX_Organizations_ParentOrganizationId" ON "Organizations" ("ParentOrganizationId");

CREATE UNIQUE INDEX "IX_RfSubjects_Guid" ON "RfSubjects" ("Guid");

SELECT setval(
    pg_get_serial_sequence('"BillPoints"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "BillPoints") + 1,
        nextval(pg_get_serial_sequence('"BillPoints"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Organizations"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Organizations") + 1,
        nextval(pg_get_serial_sequence('"Organizations"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"RfSubjects"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "RfSubjects") + 1,
        nextval(pg_get_serial_sequence('"RfSubjects"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210323115322_init', '5.0.2');

COMMIT;

START TRANSACTION;

CREATE TABLE "MeterPoint" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Guid" uuid NOT NULL,
    CONSTRAINT "PK_MeterPoint" PRIMARY KEY ("Id")
);

CREATE TABLE "BillPointToMeterPoint" (
    "BillPointId" integer NOT NULL,
    "MeterPointId" integer NOT NULL,
    "SDate" Date NOT NULL,
    "EDate" Date NULL,
    CONSTRAINT "PK_BillPointToMeterPoint" PRIMARY KEY ("BillPointId", "MeterPointId", "SDate"),
    CONSTRAINT "FK_BillPointToMeterPoint_BillPoints_BillPointId" FOREIGN KEY ("BillPointId") REFERENCES "BillPoints" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_BillPointToMeterPoint_MeterPoint_MeterPointId" FOREIGN KEY ("MeterPointId") REFERENCES "MeterPoint" ("Id") ON DELETE CASCADE
);

UPDATE "BillPoints" SET "Guid" = '954b7565-20ff-4321-9e8c-8e890953598a'
WHERE "Id" = 1;

UPDATE "BillPoints" SET "Guid" = 'ed2e5591-c148-4688-bd7c-f4250fa93165'
WHERE "Id" = 2;

UPDATE "BillPoints" SET "Guid" = '96351e37-a7f4-4734-b77f-47d55f294090'
WHERE "Id" = 3;

INSERT INTO "MeterPoint" ("Id", "Guid", "Name")
VALUES (1, '1245249a-4b74-48fd-b635-8c10f2660b55', 'ТИ-11');
INSERT INTO "MeterPoint" ("Id", "Guid", "Name")
VALUES (2, 'f1156e79-9343-4598-95c9-57bb6e0b4dbd', 'ТИ-12');
INSERT INTO "MeterPoint" ("Id", "Guid", "Name")
VALUES (3, '4fe44c30-8ead-421a-8689-9c7be542b38e', 'ТИ-21');
INSERT INTO "MeterPoint" ("Id", "Guid", "Name")
VALUES (4, '0125044e-87d2-4e46-befe-c29ec4925608', 'ТИ-31');

UPDATE "Organizations" SET "Guid" = '76a1020f-a289-4950-858d-8cd08fbe8a27'
WHERE "Id" = 1;

UPDATE "Organizations" SET "Guid" = 'fd177c31-2e33-489c-9e94-c109e5817396'
WHERE "Id" = 2;

UPDATE "Organizations" SET "Guid" = 'b576d00e-f058-430c-92d2-4f7bdfc78956'
WHERE "Id" = 3;

UPDATE "Organizations" SET "Guid" = 'c9e54849-c6f7-4ce8-adb1-7adfeaa2fd8d'
WHERE "Id" = 4;

UPDATE "Organizations" SET "Guid" = '0b7e4010-f5e0-4736-aa61-007d3bf52cb1'
WHERE "Id" = 5;

UPDATE "RfSubjects" SET "Guid" = '3644330d-dc56-4a37-a23d-a8528132a41b'
WHERE "Id" = 1;

UPDATE "RfSubjects" SET "Guid" = '6dc9ea60-5b2c-4287-a65f-4f8d3ebaa144'
WHERE "Id" = 2;

UPDATE "RfSubjects" SET "Guid" = '9b252216-0b32-4cf9-beca-da333de98e6c'
WHERE "Id" = 3;

INSERT INTO "BillPointToMeterPoint" ("BillPointId", "MeterPointId", "SDate", "EDate")
VALUES (1, 1, DATE '2021-03-23', NULL);
INSERT INTO "BillPointToMeterPoint" ("BillPointId", "MeterPointId", "SDate", "EDate")
VALUES (1, 2, DATE '2021-03-23', NULL);
INSERT INTO "BillPointToMeterPoint" ("BillPointId", "MeterPointId", "SDate", "EDate")
VALUES (2, 3, DATE '2021-03-23', DATE '2021-04-02');
INSERT INTO "BillPointToMeterPoint" ("BillPointId", "MeterPointId", "SDate", "EDate")
VALUES (3, 4, DATE '2021-03-13', NULL);

CREATE INDEX "IX_BillPointToMeterPoint_MeterPointId" ON "BillPointToMeterPoint" ("MeterPointId");

SELECT setval(
    pg_get_serial_sequence('"MeterPoint"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "MeterPoint") + 1,
        nextval(pg_get_serial_sequence('"MeterPoint"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210323131502_billpointtometerpoint_added', '5.0.2');

COMMIT;


